defaults:
  -
    scope:
      path: "" # empty string indicates a scope of ALL files
    values:
      title: "Shevy | A Vertical Rhythm Sass Library"
      layout: "default"
baseurl: '/shevy'
exclude: [
    'assets/',
    'node_modules/',
    'Gemfile',
    'Gemfile.lock',
    'Gruntfile.js',
    'package.json'
  ]
